---
title: "Publications"
page-layout: full
format:
  html:
    link-citations: true
---

## Journal Articles

### Published
- Golden<sup>g</sup>, JE, JG Barnes, and PJ Williams<sup>s</sup>. 2025. Estimating Survival and Population Trajectories of Golden Eagles in Nevada. *Journal of Raptor Research*.
- Brockman<sup>g</sup>, JC, PS Coates, JC Tull, ST O'Neil, and PJ Williams<sup>s</sup>. 2025* The effects of breeding status on common raven movement, home range, and habitat selection. *The Journal of Wildlife Management* 89:e70004.
- Wann, G, A Whipple, E Orning, M McLachlan, J Beck, PS Coates, C Conway, J Dinkins, A Johnston, C Hagen, P Makela, D Naugle, M Schroeder, J Sedinger, B Walker, PJ Williams, R Inman, C Aldridge. 2025. Greater sage-grouse seasonal habitat associations: A review and considerations for interpretation and management applications. *The Journal of Wildlife Management* 89:e70022. 
- Shoemaker, KT, H Reich, PJ Williams, M Osterhout, J Vasquez, J Beckmann, C Lackey, KM Stewart. 2025. Late season frosts and changing snowpack may exacerbate human-bear conflicts. *Ecosphere* 16:e70379
- Eisaguirre, JM, MG Lohman<sup>g</sup>, GG Frye, HE Johnson, TV Riecke, & PJ Williams<sup>s</sup>. 2025. Estimating spatially explicit survival and mortality risk from telemetry data with thinned point process models. *Ecology Letters* 28:e70092. 

- Eisaguirre<sup>p</sup>, JM, PJ Williams<sup>s</sup>, and MB Hooten. 2024. Rayleigh step-selection functions and connections to coninuous-time mechanistic movement models. *Movement Ecology*. 12:14 pages. 
- Blum<sup>p</sup>, ME, JR Bennett, FE Buderman, KM Stewart, M Cox, and PJ Williams<sup>s</sup>. 2024. Comparing contemorary models to traditional indices to estimate abundance of desert bighorn sheep. *Journal of Wildlife Management*. 88:e22517. 
- Eisaguirre<sup>p</sup>, JM, PJ Williams<sup>s</sup>, X Lu, ML Kissling, PA Schuette, BP Weitzman, WS Beatty, GG Esslinger, JN Womble, and MB Hooten. 2023. Informing management of recovering predators and their prey with ecological diffusion models. *Frontiers in Ecology and the Environment*. 21:479–488.
- Eisaguirre<sup>p</sup>, JM, PJ Williams<sup>s</sup>, JC Brockman<sup>g</sup>, SB Lewis, C Barger, G Breed, and T Booms. 2023. A hierarchical modeling framework for estimating individual- and population-level reproductive success from movement data. *Methods in Ecology and Evolution*. 14:2110–2122. 
- Keating<sup>g</sup>, MP, PJ Williams<sup>s</sup>, JR Robb, FE Buderman, JP Lewis, T Vanosdol, and R Harer<sup>u</sup>. 2023. Henslow's sparrow shows positive response to prescribed fire rotation. *Ornithological Applications*. 125, duad018. 
- Williams<sup>s</sup>, PJ, X Lu, HR Scharf, and MB Hooten. 2023. Embracing Asymmetry in Nature: How to account for skewness in ecological data. *Ecological Informatics* 75:102085. 
- Riecke<sup>p</sup>, TV, MG Lohman<sup>g</sup>, BS Sedinger<sup>p</sup>, TW Arnold, C Feldheim, DN Koons, F Rohwer, M Schaub, PJ Williams, and JS Sedinger. 2022. Density-dependence produces spurious relationships among demographic parameters in harvested species. *Journal of Animal Ecology* 91:2261–2272. [(Open Access)](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13807)
- Ellis<sup>u</sup>, S, TV Riecke<sup>p</sup>, MG Lohman<sup>g</sup>, PJ Williams, JS Sedinger. 2022. Long-term trends and drought: spatiotemporal variation in juvenile sex ratios of North American ducks. *Ecology and Evolution* 12:e9099. [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1002/ece3.9099)
- Riecke<sup>p</sup>, TV, BS Sedinger<sup>p</sup>, TW Arnold, D Gibson, DN Koons, MG Lowhman<sup>g</sup>, M Schaub, PJ Williams, and JS Sedinger. 2022. A hierarchical model for jointly assessing ecological and anthropogenic impacts on animal demography. *Journal of Animal Ecology* 91:1612–1626.  [(Open Access)](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13747)
- Street<sup>p</sup>, PA, TV Riecke<sup>p</sup>, PJ Williams, TL Behnke, and JS Sedinger. 2022. Estimating survival and adoption rates of dependent juveniles. *Ecology and Evolution* 12:e9005. [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1002/ece3.9005)
- Koons, DN, TV Riecke<sup>p</sup>, GS Boomer, BS Sedinger<sup>p</sup>, JS Sedinger, PJ Williams, and TW Arnold. 2022. A niche model in adaptive resource management. *Ecology and Evolution* 12:e8541. [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1002/ece3.8541)
- Scharf, HR, X Lu, PJ Williams, and MB Hooten. 2022. Constructing flexible, identifiable, and interpretable statistical models for binary data. *International Statistical Review* 90:328–345. [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/scharf2022constructing.pdf)
- O’Neil, ST, PS Coates, JC Brockman<sup>g</sup>, PJ Jackson, JO Spencer, and PJ Williams<sup>s</sup>. 2021. Inter- and intra-annual effects of lethal removal on common raven abundance in Nevada and California, USA. *Human–Wildlife Interactions* 15:Iss.3, Article 20.  [(Open Access)](https://doi.org/10.26077/p79d-en84)
- Lohman<sup>g</sup>, MG, TV Riecke<sup>p</sup>, PJ Williams, and JS Sedinger. 2021. Individual heterogeneity in fitness in a long-lived herbivore. *Ecology and Evolution* 11:15164–15173.  [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1002/ece3.8197)
- Leach, CB, PJ Williams, JM Eisaguirre<sup>p</sup>, JN Womble, MR Bower, and MB Hooten. 2021. Recursive Bayesian computation facilitates adaptive optimal design in ecological studies. *Ecology* 103:e03573.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/leach2021recurrsive.pdf)
- Eisaguirre<sup>p</sup>, JM, PJ Williams<sup>s</sup>, X Lu, M Kissling, W. Beatty, GG Esslinger, JN Womble, and MB Hooten. 2021. Diffusion modeling reveals effects of multiple release sites and human activity on a recolonizing apex predator. *Movement Ecology* 9:34.  [(Open Access)](https://movementecologyjournal.biomedcentral.com/articles/10.1186/s40462-021-00270-w)
- Womble, JN, PJ Williams<sup>s</sup>, RW McNabb, A Prakash, R Gens, BS Sedinger<sup>p</sup>, and CR Acevedo<sup>g</sup>. 2021. Harbor seals as sentinels of Ice Dynamics in Tidewater Glacier Fjords. *Frontiers in Marine Science* 8:634541.  [(Open Access)](https://www.frontiersin.org/articles/10.3389/fmars.2021.634541/full)
- Acevedo<sup>g</sup> CR, TV Riecke<sup>p</sup>, AG Leach, MG Lohman<sup>g</sup>, PJ Williams, and JS Sedinger. 2020. Long-term research and hierarchical models reveal consistent fitness costs of being the last egg in a clutch. *Journal of Animal Ecology* 89:1978–1987.  [(Open Access)](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13232)
- Williams, PJ<sup>s</sup>, C Schroeder, PJ Jackson. 2020. Estimating reproduction and survival of unmarked juveniles using aerial images and marked adults. *Journal of Agricultural, Biological and Environmental Statistics* 25:133–147.  [(Open Access)](https://link.springer.com/article/10.1007/s13253-020-00384-5)
- Lu, Xinyi, PJ Williams, MB Hooten, JA Powell, JN Womble, and MR Bower. 2020. Nonlinear reaction-diffusion process models improve inference for population dynamics. *Environmetrics* 31:e2604.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/lu2020nonlinear.pdf)
- Riecke<sup>p</sup>, TV, BS Sedinger<sup>p</sup>, PJ Williams, AG Leach, and JS Sedinger. 2019. Estimating correlations among demographic parameters in population models. *Ecology and Evolution* 9:13521–13531.  [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1002/ece3.5809)
- Williams, PJ, WL Kendall, and MB Hooten. 2019. Selecting ecological models using multi-objective optimization. *Ecological Modelling* 404:21–26.  [(Open Access)](https://www.sciencedirect.com/science/article/pii/S0304380019301577?via%3Dihub)
- Riecke<sup>p</sup>, TV, PJ Williams<sup>s</sup>, TL Behnke, D Gibson, AG Leach, BS Sedinger<sup>p</sup>, PA Street, and JS Sedinger. 2019. Integrated population models: model assumptions and inference. *Methods in Ecology and Evolution* 10:1072–1082.  [(Free Access)](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13195)
- Williams<sup>s</sup>, PJ, MB Hooten, GG Esslinger, JN Womble, JL Bodkin, and MR Bower. 2019. The rise of an apex predator following deglaciation. *Diversity and Distributions* 25:895–908.  [(Open Access)](https://onlinelibrary.wiley.com/doi/10.1111/ddi.12908)
- Conn, PB, DS Johnson, PJ Williams, SR Melin, and MB Hooten. 2018. A guide to Bayesian model checking for ecologists. *Ecological Monographs* 88:526–542.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/conn2018guide.pdf)
- Williams<sup>s</sup>, PJ, MB Hooten, GG Esslinger, JN Womble, and MR Bower. 2018. Monitoring dynamic spatio-temporal ecological processes optimally. *Ecology* 99:524–535.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2018monitoring.pdf)
- Williams, PJ, MB Hooten, JN Womble, and MR Bower. 2017. Estimating occupancy and abundance using aerial images with imperfect detection. *Methods in Ecology and Evolution* 8:1679–1689.  [(Free Access)](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12815)
- Williams, PJ, MB Hooten, JN Womble, GG Esslinger, and MR Bower. 2017. An integrated data model to estimate spatio-temporal occupancy, abundance, and colonization dynamics. *Ecology* 98:328–336.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2017integrated.pdf)
- Hefley, TJ, KM Broms, BM Brost, FE Buderman, SL Kay, HR Scharf, JR Tipton, PJ Williams, and MB Hooten. 2017. The basis function approach to modeling autocorrelation in ecological data. *Ecology* 98:632–646. [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/hefley2017basis.pdf)
- Williams, PJ, and WL Kendall. 2017. A guide to multi-objective optimization for ecologists with an application to cackling goose management. *Ecological Modelling* 343:54–67.  [(Open Access)](https://www.sciencedirect.com/science/article/pii/S0304380016305610?via%3Dihub)
- Williams, PJ and MB Hooten. 2016. Combining statistical inference and decisions in ecology. *Ecological Applications* 26:1930–1942.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2016combining.pdf)
- Crimmins, SM, PC McKann, JR Robb, JP Lewis, T Vanosdol, BA Walker, PJ Williams and WE Thogmartin. 2016. Factors affecting Henslow's sparrow (*Ammodramus henslowii*) nest survival in southern Indiana. *Wilson Journal of Ornithology* 128. [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/crimmins2016factors.pdf)
- Vigil, E, MKR Christianson, JM Lepak, and PJ Williams. 2016. Temperature effects on hatching and viability of juvenile gill lice, *Salmincola californiensis*. *Journal of Fish Diseases* 39:899–905.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/vigel2016temperature.pdf)
- Gerber, BD, PJ Williams, and LL Bailey. 2014. Primates and Cameras: Non-invasive sampling to make population-level inferences while accounting for imperfect detection. *International Journal of Primatology* 35:841–858.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/gerber2014noninvasive.pdf)
- Williams, PJ, SH Whitmore, and RJ Gutiérrez. 2014. Use of private lands for foraging by California spotted owls in the central Sierra Nevada. *Wildlife Society Bulletin* 38:705–709.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2014use.pdf)
- Williams, PJ, NJ Engbrecht, JR Robb, and VCK Terrell, and M. J. Lannoo. 2013. Surveying a threatened amphibian species through a narrow detection window. *Copeia* 2013:552–561.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2013surveying.pdf)
- Engbrecht, NJ, MJ Lannoo, PJ Williams, JR Robb, T Gerardot, DR Karns, and M Lodato. 2013. Is there hope for the Hoosier Frog? An update on the status of Crawfish Frogs (*Lithobates areolatus*) in Indiana, with recommendations for their conservation. *Proceedings of the Indiana Academy of Science* 121:147–157.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/engbrecht2013hope.pdf)
- Heemeyer, JL, PJ Williams, and MJ Lannoo. 2012. Obligate crayfish burrow use and core habitat requirements of crawfish frogs. *Journal of Wildlife Management* 76:1081–1091.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/heemeyer2012obligate.pdf)
- Williams, PJ, JR Robb, and DR Karns. 2012. Habitat selection by crawfish frogs (*Lithobates areolatus*) in a large mixed grassland/forest habitat. *Journal of Herpetology* 46:682–688.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2012habitat.pdf)
- Williams, PJ, JR Robb, and DR Karns. 2012. Occupancy dynamics of breeding crawfish frogs in southeastern Indiana. *Wildlife Society Bulletin* 36:350–357.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/Williams2012occupancy.pdf)
- Williams, PJ, JR Robb, RH Kappler, TE Piening, and DR Karns. 2012. Intraspecific density dependence in larval development of the crawfish frog, *Lithobates areolatus*. *Herpetological Review* 43:36–38.  [(PDF)](https://www.perrywilliams.us/wp-content/uploads/2018/03/williams2012intraspecific.pdf)
- Williams, PJ, RJ Gutiérrez, and S Whitmore. 2011. Home range and habitat selection of the spotted owl in the central Sierra Nevada. *Journal of Wildlife Management* 75:333–343.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/williams2012home.pdf)
- Hoffman, AS, J Heemeyer, PJ Williams, JR Robb, DR Karns, and MJ Lannoo. 2010. Strong site fidelity and a variety of imaging techniques reveal activity patterns in crawfish frogs (*Lithobates areolatus*), a species of conservation concern. *BioScience* 60:829–834.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/hoffman2010strong.pdf)
- Schook, DM, MD Collins, WE Jensen, PJ Williams, NE Bader, and TH Parker. 2008. Geographic patterns of song similarity in the Dickcissel. *The Auk* 125:953–964.  [(PDF)](http://www.perrywilliams.us/wp-content/uploads/2023/05/schook2008geographic.pdf)

## Book Chapters

- Gerber, BD, and PJ Williams. 2020. Decision-making and monitoring strategies in natural resource management and conservation. In Wang, Yeqiao (Ed.), *Terrestrial Ecosystems and Biodiversity*, 2nd Edition. CRC Press.

## Graduate Student Theses

- Golden<sup>g</sup>, J. 2023. *Use and survival of greater sage-grouse in meadows managed for non-native ungulate grazing in Nevada*. University of Nevada, Reno. M.S. Thesis.
- Byrne<sup>g</sup>, M. 2023. *Examining the impact of mercury on waterfowl population dynamics with implications for human health and water management in arid environments*. University of Nevada, Reno. M.S. Thesis.
- Acevedo<sup>g</sup>, CR. 2021. *Spatio-temporal population dynamics of Nevada greater sage-grouse from 2000–2018*. University of Nevada, Reno. M.S. Thesis.
- Keating<sup>g</sup>, MP. 2021. *Estimating spatial locations of attraction through time with animal movement data*. University of Nevada, Reno. M.S. Thesis.

## Extension Publications

- Williams, PJ. 2017. Monitoring the distribution and abundance of sea otters. *Methods in Ecology and Evolution* Blog. [(Link)](https://methodsblog.wordpress.com/2017/09/26/monitoring-sea-otters/#more-6064)
- Womble, JN, PJ Williams, MB Hooten, LF Taylor-Thomas, W Johnson, and MR Bower. 2017. Protocol for monitoring the abundance and spatial distribution of sea otters in Glacier Bay National Park & Preserve, Alaska. National Park Service, Natural Resource Report.
- Williams, PJ, and MB Hooten. 2017. The extraordinary return of sea otters to Glacier Bay. *The Conversation*. [(Link)](https://theconversation.com/the-extraordinary-return-of-sea-otters-to-glacier-bay-74909)
- Williams, PJ. 2017. Monitoring the sea otters in Glacier Bay National Park. *The Wildlife Management Institute*. [(Link)](https://wildlifemanagement.institute/outdoor-news-bulletin/february-2017/monitoring-sea-otters-glacier-bay-national-park)
- Williams, PJ. 2015. *Methods for incorporating population dynamics and decision theory in cackling goose management*. Ph.D. Dissertation, Colorado State University. Fort Collins, CO.
- Williams, PJ. 2015. *Combining statistical inference and decisions in ecology*. M.S. Thesis, Colorado State University. Fort Collins, CO.
- Williams, PJ. 2015. Structured decision making for setting the population objective and management trigger points of cackling geese: report to the Pacific Flyway, cackling goose sub-committee.
- Lesmeister, DB, S Blomquist, EV Lonsdorf, D Wood, PJ Williams, B Pendley, KE Mangan, BA Walker. 2014. Forest invasive adaptive management on National Wildlife Refuge Lands in the central hardwood region. *Proceedings of the 19th Central Hardwood Forest Conference* 19:22–35.
- Williams, PJ. 2008. *Home range and foraging habitat selection of spotted owls in the central Sierra Nevada*. M.S. Thesis, University of Minnesota. St. Paul, MN.
- Gutiérrez, RJ, S Whitmore, ME Seamans, G Zimmerman, PJ Williams, and P Stine. 2008. Acute effects of canopy reduction on California spotted owls: challenges for adaptive management. Technical Report to USFS.
