name: Build & Deploy LaTeX → Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      - name: Build site
        run: |
          mkdir -p _site
          # Convert each .tex in root to HTML content
          for f in *.tex; do
            [ -e "$f" ] || continue
            base="${f%.tex}"
            pandoc "$f" -s -t html5 --mathjax -o "_site/${base}.content.html"
            cat _shell_top.html "_site/${base}.content.html" _shell_bottom.html > "_site/${base}.html"
            rm "_site/${base}.content.html"
          done
          # Copy assets
          mkdir -p _site/assets
          cp -r assets/* _site/assets/ 2>/dev/null || true
          # Preserve custom domain if present
          [ -f CNAME ] && cp CNAME _site/CNAME || true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
